# Generated by Django 5.0.7 on 2024-08-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='idNumber',
        ),
        migrations.AddField(
            model_name='user',
            name='businessNumber',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
