# Generated by Django 5.0.7 on 2024-08-04 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_businessnumber_alter_user_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='isSocialUser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='authType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.authtype'),
        ),
        migrations.CreateModel(
            name='SocialUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('naver', 'Naver'), ('kakao', 'Kakao'), ('google', 'Google')], max_length=10)),
                ('userFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
