# Generated by Django 5.0.7 on 2024-08-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_authtype_user_issocialuser_user_authtype_socialuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='provider',
            field=models.CharField(choices=[('naver', 'naver'), ('kakao', 'kakao'), ('google', 'google')], max_length=10),
        ),
    ]
