# Generated by Django 5.0.7 on 2024-08-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_socialuser_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='businessNumber',
        ),
        migrations.AddField(
            model_name='user',
            name='businessInfo',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
