# Generated by Django 5.0.7 on 2024-08-09 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='grade',
            new_name='gradeFK',
        ),
    ]
