# Generated by Django 5.0.7 on 2024-08-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("popup", "0002_remove_brands_followers"),
        ("user", "0011_rename_grade_user_gradefk"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="followed",
            field=models.ManyToManyField(related_name="followers", to="popup.brands"),
        ),
    ]
