# Generated by Django 5.0.7 on 2024-08-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0013_user_saved_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="saved_popup",
            field=models.JSONField(default=dict),
        ),
    ]
