# Generated by Django 5.0.7 on 2024-08-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0014_user_saved_popup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="saved_popup",
            field=models.JSONField(default=list),
        ),
    ]
