# Generated by Django 5.0.7 on 2024-08-14 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0016_rename_saved_popup_user_savedpopup"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="saved_product",
            new_name="savedProduct",
        ),
    ]
