# Generated by Django 5.0.7 on 2024-08-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_user_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changeInfo', models.CharField(max_length=10)),
            ],
        ),
    ]
