# Generated by Django 5.0.7 on 2024-08-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0020_remove_user_point_pointhistory_pointchangefk"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("addressName", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=12)),
                ("phoneNumber", models.IntegerField(max_length=11)),
                ("postNumber", models.IntegerField(max_length=6)),
                ("address", models.TextField()),
                ("detailAddress", models.TextField()),
            ],
        ),
    ]
