# Generated by Django 5.0.7 on 2024-08-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_remove_user_point_pointhistory_pointchangefk'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileImage',
            field=models.TextField(default='/_next/static/media/dummy_profile.1b80edaa.jpg'),
        ),
    ]
