# Generated by Django 5.0.7 on 2024-08-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0021_useraddress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraddress",
            name="phoneNumber",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="postNumber",
            field=models.IntegerField(),
        ),
    ]
