# Generated by Django 5.0.7 on 2024-08-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_user_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileImage',
            field=models.TextField(default='/images/dummy/dummy_profile.jpg'),
        ),
    ]
