# Generated by Django 5.0.7 on 2024-08-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0023_useraddress_userfk"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraddress",
            name="default",
            field=models.BooleanField(default=False),
        ),
    ]
