# Generated by Django 5.0.7 on 2024-08-20 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0025_usergrade_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraddress",
            name="phoneNumber",
            field=models.CharField(max_length=11),
        ),
    ]
