# Generated by Django 5.0.7 on 2024-08-20 07:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0022_alter_user_profileimage"),
        ("user", "0027_alter_useraddress_postnumber"),
    ]

    operations = []
