# Generated by Django 5.0.7 on 2024-09-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0028_merge_20240820_1637"),
    ]

    operations = [
        migrations.AddField(
            model_name="user", name="recent", field=models.JSONField(default=dict),
        ),
    ]
