# Generated by Django 5.0.7 on 2024-09-04 08:14

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0029_user_recent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="recent",
            field=models.JSONField(default=user.models.default_recent),
        ),
    ]
