# Generated by Django 5.0.7 on 2024-08-09 08:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("popup", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brands",
            name="followers",
        ),
    ]
