# Generated by Django 5.0.7 on 2024-08-14 14:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("popup", "0004_brands_follower_product_saved"),
    ]

    operations = [
        migrations.RenameField(
            model_name="brands",
            old_name="follower",
            new_name="saved",
        ),
    ]
