# Generated by Django 5.0.7 on 2024-08-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("popup", "0007_remove_product_discription_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="brands",
            name="description",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
