# Generated by Django 5.0.7 on 2024-08-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("popup", "0010_alter_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="brands",
            name="thumbnail",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
