# Generated by Django 5.0.7 on 2024-08-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("popup", "0011_brands_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="amount",
            field=models.IntegerField(default=0),
        ),
    ]
