# Generated by Django 5.0.7 on 2024-08-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("popup", "0012_cart_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="amount",
        ),
        migrations.AddField(
            model_name="cart",
            name="option",
            field=models.JSONField(default=dict),
        ),
    ]
