# Generated by Django 5.0.7 on 2024-08-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("popup", "0014_remove_cart_totalprice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="currency",
        ),
        migrations.AddField(
            model_name="ordercs",
            name="delivery",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
