# Generated by Django 5.0.7 on 2024-08-19 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("popup", "0015_remove_order_currency_ordercs_delivery"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="name",
        ),
    ]
