# Generated by Django 5.0.7 on 2024-08-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("popup", "0016_remove_order_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="totalDiscount",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
