# Generated by Django 5.0.7 on 2024-08-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("popup", "0017_order_totaldiscount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="deliveryRequest",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
