# Generated by Django 5.0.7 on 2024-08-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("popup", "0019_courier_rename_deliveryrequest_order_deliveryfk_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="totalDiscount",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
