# Generated by Django 5.0.7 on 2024-08-24 09:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("popup", "0020_alter_order_totaldiscount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brands",
            name="name",
        ),
    ]
