# Generated by Django 5.0.7 on 2024-08-25 16:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("popup", "0021_remove_brands_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brands",
            name="proceeding",
        ),
    ]
