# Generated by Django 5.0.7 on 2024-08-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("popup", "0022_remove_brands_proceeding"),
    ]

    operations = [
        migrations.AddField(
            model_name="brands",
            name="view",
            field=models.IntegerField(default=0),
        ),
    ]
