# Generated by Django 5.0.7 on 2024-08-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popup', '0023_brands_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brands',
            name='thumbnail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
